import { Providers } from '@/providers/provider';
import type { Metadata } from 'next';
import '../globals.css';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <Suspense fallback={<div>Loading authentication content...</div>}>
        {children}
      </Suspense>
    </Providers>
  );
}
