version: '3.8'
services:
  db:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xincere_blog
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000' # APIアクセス用
      - '9001:9001' # 管理コンソール用
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminroot
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run dev"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/xincere_blog

volumes:
  pg_data:
  minio_data:
