version: '3.8'
services:
  db:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xincere_blog
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000' # APIアクセス用
      - '9001:9001' # 管理コンソール用
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminroot
    command: server /data --console-address ":9001"
  create-buckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadminroot;
      mc mb local/xincere-blog;
      mc policy set public local/xincere-blog;  # バケットをPublicに設定
      echo 'Bucket created and set to public access';
      exit 0;
      "
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
